### ISSUE TITLE
confusion around PRESHARED_AUTH_HEADER_VALUE

### ISSUE THREAD

**Issue by ajayanaj** [kyouheicf/logpush-grafana-loki#1]
HI,

I just came across this repo and really interested to implement within our company. When reading the installation I got stuck this variable "PRESHARED_AUTH_HEADER_VALUE" I couldn't figure out this variable. It would be helpful for us if you can bit clarify on this. 

Once again thanks alot for opensourcing the code.

**Comment by kyouheicf** [comment]
@ajayanaj Thank you for trying to leverage my idea, which is based on Logpush to HTTP destination.
https://developers.cloudflare.com/logs/get-started/enable-destinations/http/

For HTTP destination, we usually put authentication header as we ensure only we are pushing data.
So, `PRESHARED_AUTH_HEADER_VALUE` can be whatever the secret string that only you can know in advance.

I'm happy to hear any other question or comment from you, thanks!

**Comment by ajayanaj** [comment]
@kyouheicf  Thanks for the the response. We tried with and getting the below error.
"error validating destination: error writing object: error uploading to https: 403 error code: 1003"
This is our destination conf: "https://logpush-grafana-loki.software-ag-webmethods.workers.dev?header_X-Logpush-Auth=mypresharedkey&tags=host:mydomain.com,dataset:http_requests

Since the error has 403, is it something wrong with the PRESHARED_AUTH_HEADER_VALUE? we were able to create the worker without any error using the same PRESHARED_AUTH_HEADER_VALUE. 

Can you please help here?

**Comment by kyouheicf** [comment]
@ajayanaj If you have changed `const PRESHARED_AUTH_HEADER_VALUE = 'mypresharedkey';`, your Logpush configuration should be changed as well.
Can you try with your changed preshared key?
I mean `header_X-Logpush-Auth=your_changed_preshared_key_string` part in `destination_conf`.

When I try your workers endpoint, it says that `X-Logpush-Auth` value does not match, which is configured on your Workers code.

```
% curl "https://logpush-grafana-loki.software-ag-webmethods.workers.dev" -X POST \
--data-raw '{"content":"test","filename":"test.txt"}' \
-H "Content-Type: application/json" \
-H "X-Logpush-Auth: mypresharedkey"
Sorry, you have submitted an invalid key.
```

**Comment by ajayanaj** [comment]
@kyouheicf  Sorry for the late response as I was out of the town for few days. 
We were able to solve the issue, it was the variable we created. 
Once again thanks for the contribution.

**Comment by kyouheicf** [comment]
@ajayanaj thank you for looking up my code in detail, too 😄
